version: "3"
services:
  bot:
    environment:
      DATABASE_URL: mysql://myuser:mypassword@mysql:3306/mydb
    build:
      context: .
      dockerfile: ./apps/discord-bot/Dockerfile
    ports:
      - 8080:8080
  mysql:
    container_name: senchabot_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
