// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BotActionActivity struct {
	ID               string     `json:"id"`
	BotPlatformType  string     `json:"botPlatformType"`
	BotActivity      string     `json:"botActivity"`
	DiscordServerID  *string    `json:"discordServerID,omitempty"`
	TwitchChannelID  *string    `json:"twitchChannelID,omitempty"`
	ActivityAuthor   *string    `json:"activityAuthor,omitempty"`
	ActivityAuthorID *string    `json:"activityAuthorID,omitempty"`
	ActivityDate     *time.Time `json:"activityDate,omitempty"`
}

type BotCommand struct {
	ID              string     `json:"id"`
	CommandName     string     `json:"commandName"`
	CommandContent  string     `json:"commandContent"`
	TwitchChannelID *string    `json:"twitchChannelID,omitempty"`
	DiscordServerID *string    `json:"discordServerID,omitempty"`
	CreatedBy       *string    `json:"createdBy,omitempty"`
	UpdatedBy       *string    `json:"updatedBy,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
}

type BotCommandAlias struct {
	ID              string     `json:"id"`
	CommandAlias    string     `json:"commandAlias"`
	CommandName     string     `json:"commandName"`
	TwitchChannelID *string    `json:"twitchChannelID,omitempty"`
	DiscordServerID *string    `json:"discordServerID,omitempty"`
	CreatedBy       *string    `json:"createdBy,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
}

type TwitchChannel struct {
	ID          string  `json:"id"`
	ChannelID   string  `json:"channelID"`
	ChannelName string  `json:"channelName"`
	UserID      *string `json:"userID,omitempty"`
}
