// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: botcommand.proto

package botcommand

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CommandName    string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandContent string                 `protobuf:"bytes,3,opt,name=command_content,json=commandContent,proto3" json:"command_content,omitempty"`
	CommandType    int32                  `protobuf:"varint,4,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Status         int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BotCommand) Reset() {
	*x = BotCommand{}
	mi := &file_botcommand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCommand) ProtoMessage() {}

func (x *BotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCommand.ProtoReflect.Descriptor instead.
func (*BotCommand) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{0}
}

func (x *BotCommand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BotCommand) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *BotCommand) GetCommandContent() string {
	if x != nil {
		return x.CommandContent
	}
	return ""
}

func (x *BotCommand) GetCommandType() int32 {
	if x != nil {
		return x.CommandType
	}
	return 0
}

func (x *BotCommand) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BotCommand) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *BotCommand) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *BotCommand) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateBotCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandName    string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandContent string                 `protobuf:"bytes,3,opt,name=command_content,json=commandContent,proto3" json:"command_content,omitempty"`
	BotPlatformId  string                 `protobuf:"bytes,4,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBotCommandRequest) Reset() {
	*x = CreateBotCommandRequest{}
	mi := &file_botcommand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotCommandRequest) ProtoMessage() {}

func (x *CreateBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBotCommandRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateBotCommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *CreateBotCommandRequest) GetCommandContent() string {
	if x != nil {
		return x.CommandContent
	}
	return ""
}

func (x *CreateBotCommandRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

func (x *CreateBotCommandRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateBotCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoText      string                 `protobuf:"bytes,1,opt,name=info_text,json=infoText,proto3" json:"info_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotCommandResponse) Reset() {
	*x = CreateBotCommandResponse{}
	mi := &file_botcommand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotCommandResponse) ProtoMessage() {}

func (x *CreateBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotCommandResponse.ProtoReflect.Descriptor instead.
func (*CreateBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBotCommandResponse) GetInfoText() string {
	if x != nil {
		return x.InfoText
	}
	return ""
}

type UpdateBotCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Platform       string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandName    string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandContent string                 `protobuf:"bytes,3,opt,name=command_content,json=commandContent,proto3" json:"command_content,omitempty"`
	BotPlatformId  string                 `protobuf:"bytes,4,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateBotCommandRequest) Reset() {
	*x = UpdateBotCommandRequest{}
	mi := &file_botcommand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBotCommandRequest) ProtoMessage() {}

func (x *UpdateBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBotCommandRequest.ProtoReflect.Descriptor instead.
func (*UpdateBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBotCommandRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateBotCommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *UpdateBotCommandRequest) GetCommandContent() string {
	if x != nil {
		return x.CommandContent
	}
	return ""
}

func (x *UpdateBotCommandRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

func (x *UpdateBotCommandRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateBotCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandName   string                 `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	InfoText      string                 `protobuf:"bytes,2,opt,name=info_text,json=infoText,proto3" json:"info_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBotCommandResponse) Reset() {
	*x = UpdateBotCommandResponse{}
	mi := &file_botcommand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBotCommandResponse) ProtoMessage() {}

func (x *UpdateBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBotCommandResponse.ProtoReflect.Descriptor instead.
func (*UpdateBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBotCommandResponse) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *UpdateBotCommandResponse) GetInfoText() string {
	if x != nil {
		return x.InfoText
	}
	return ""
}

type GetGlobalBotCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandName   string                 `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalBotCommandRequest) Reset() {
	*x = GetGlobalBotCommandRequest{}
	mi := &file_botcommand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalBotCommandRequest) ProtoMessage() {}

func (x *GetGlobalBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalBotCommandRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{5}
}

func (x *GetGlobalBotCommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

type GetGlobalBotCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *BotCommand            `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalBotCommandResponse) Reset() {
	*x = GetGlobalBotCommandResponse{}
	mi := &file_botcommand_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalBotCommandResponse) ProtoMessage() {}

func (x *GetGlobalBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalBotCommandResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{6}
}

func (x *GetGlobalBotCommandResponse) GetCommand() *BotCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type GetUserBotCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	BotPlatformId string                 `protobuf:"bytes,3,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBotCommandRequest) Reset() {
	*x = GetUserBotCommandRequest{}
	mi := &file_botcommand_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBotCommandRequest) ProtoMessage() {}

func (x *GetUserBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBotCommandRequest.ProtoReflect.Descriptor instead.
func (*GetUserBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserBotCommandRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetUserBotCommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *GetUserBotCommandRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

type GetUserBotCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *BotCommand            `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBotCommandResponse) Reset() {
	*x = GetUserBotCommandResponse{}
	mi := &file_botcommand_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBotCommandResponse) ProtoMessage() {}

func (x *GetUserBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBotCommandResponse.ProtoReflect.Descriptor instead.
func (*GetUserBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserBotCommandResponse) GetCommand() *BotCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type GetCommandListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	BotPlatformId string                 `protobuf:"bytes,2,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandListRequest) Reset() {
	*x = GetCommandListRequest{}
	mi := &file_botcommand_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandListRequest) ProtoMessage() {}

func (x *GetCommandListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandListRequest.ProtoReflect.Descriptor instead.
func (*GetCommandListRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommandListRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetCommandListRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

type GetCommandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*BotCommand          `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandListResponse) Reset() {
	*x = GetCommandListResponse{}
	mi := &file_botcommand_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandListResponse) ProtoMessage() {}

func (x *GetCommandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandListResponse.ProtoReflect.Descriptor instead.
func (*GetCommandListResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommandListResponse) GetCommands() []*BotCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type DeleteBotCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	BotPlatformId string                 `protobuf:"bytes,3,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotCommandRequest) Reset() {
	*x = DeleteBotCommandRequest{}
	mi := &file_botcommand_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotCommandRequest) ProtoMessage() {}

func (x *DeleteBotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotCommandRequest.ProtoReflect.Descriptor instead.
func (*DeleteBotCommandRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBotCommandRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeleteBotCommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *DeleteBotCommandRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

type DeleteBotCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandName   string                 `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	InfoText      string                 `protobuf:"bytes,2,opt,name=info_text,json=infoText,proto3" json:"info_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotCommandResponse) Reset() {
	*x = DeleteBotCommandResponse{}
	mi := &file_botcommand_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotCommandResponse) ProtoMessage() {}

func (x *DeleteBotCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotCommandResponse.ProtoReflect.Descriptor instead.
func (*DeleteBotCommandResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBotCommandResponse) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *DeleteBotCommandResponse) GetInfoText() string {
	if x != nil {
		return x.InfoText
	}
	return ""
}

type GetCommandAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandAlias  string                 `protobuf:"bytes,2,opt,name=command_alias,json=commandAlias,proto3" json:"command_alias,omitempty"`
	BotPlatformId string                 `protobuf:"bytes,3,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandAliasRequest) Reset() {
	*x = GetCommandAliasRequest{}
	mi := &file_botcommand_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandAliasRequest) ProtoMessage() {}

func (x *GetCommandAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandAliasRequest.ProtoReflect.Descriptor instead.
func (*GetCommandAliasRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommandAliasRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetCommandAliasRequest) GetCommandAlias() string {
	if x != nil {
		return x.CommandAlias
	}
	return ""
}

func (x *GetCommandAliasRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

type GetCommandAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandName   string                 `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandAliasResponse) Reset() {
	*x = GetCommandAliasResponse{}
	mi := &file_botcommand_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandAliasResponse) ProtoMessage() {}

func (x *GetCommandAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandAliasResponse.ProtoReflect.Descriptor instead.
func (*GetCommandAliasResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommandAliasResponse) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

type CreateCommandAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Aliases       []string               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	BotPlatformId string                 `protobuf:"bytes,4,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandAliasRequest) Reset() {
	*x = CreateCommandAliasRequest{}
	mi := &file_botcommand_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandAliasRequest) ProtoMessage() {}

func (x *CreateCommandAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandAliasRequest.ProtoReflect.Descriptor instead.
func (*CreateCommandAliasRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommandAliasRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateCommandAliasRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *CreateCommandAliasRequest) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CreateCommandAliasRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

func (x *CreateCommandAliasRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateCommandAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoText      string                 `protobuf:"bytes,1,opt,name=info_text,json=infoText,proto3" json:"info_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandAliasResponse) Reset() {
	*x = CreateCommandAliasResponse{}
	mi := &file_botcommand_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandAliasResponse) ProtoMessage() {}

func (x *CreateCommandAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandAliasResponse.ProtoReflect.Descriptor instead.
func (*CreateCommandAliasResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommandAliasResponse) GetInfoText() string {
	if x != nil {
		return x.InfoText
	}
	return ""
}

type DeleteCommandAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	CommandAlias  string                 `protobuf:"bytes,2,opt,name=command_alias,json=commandAlias,proto3" json:"command_alias,omitempty"`
	BotPlatformId string                 `protobuf:"bytes,3,opt,name=bot_platform_id,json=botPlatformId,proto3" json:"bot_platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommandAliasRequest) Reset() {
	*x = DeleteCommandAliasRequest{}
	mi := &file_botcommand_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommandAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommandAliasRequest) ProtoMessage() {}

func (x *DeleteCommandAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommandAliasRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommandAliasRequest) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCommandAliasRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeleteCommandAliasRequest) GetCommandAlias() string {
	if x != nil {
		return x.CommandAlias
	}
	return ""
}

func (x *DeleteCommandAliasRequest) GetBotPlatformId() string {
	if x != nil {
		return x.BotPlatformId
	}
	return ""
}

type DeleteCommandAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoText      string                 `protobuf:"bytes,1,opt,name=info_text,json=infoText,proto3" json:"info_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommandAliasResponse) Reset() {
	*x = DeleteCommandAliasResponse{}
	mi := &file_botcommand_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommandAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommandAliasResponse) ProtoMessage() {}

func (x *DeleteCommandAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botcommand_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommandAliasResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommandAliasResponse) Descriptor() ([]byte, []int) {
	return file_botcommand_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCommandAliasResponse) GetInfoText() string {
	if x != nil {
		return x.InfoText
	}
	return ""
}

var File_botcommand_proto protoreflect.FileDescriptor

const file_botcommand_proto_rawDesc = "" +
	"\n" +
	"\x10botcommand.proto\x12\x19senchabot.grpc.botcommand\"\x80\x02\n" +
	"\n" +
	"BotCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12'\n" +
	"\x0fcommand_content\x18\x03 \x01(\tR\x0ecommandContent\x12!\n" +
	"\fcommand_type\x18\x04 \x01(\x05R\vcommandType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xc8\x01\n" +
	"\x17CreateBotCommandRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12'\n" +
	"\x0fcommand_content\x18\x03 \x01(\tR\x0ecommandContent\x12&\n" +
	"\x0fbot_platform_id\x18\x04 \x01(\tR\rbotPlatformId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\"7\n" +
	"\x18CreateBotCommandResponse\x12\x1b\n" +
	"\tinfo_text\x18\x01 \x01(\tR\binfoText\"\xc8\x01\n" +
	"\x17UpdateBotCommandRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12'\n" +
	"\x0fcommand_content\x18\x03 \x01(\tR\x0ecommandContent\x12&\n" +
	"\x0fbot_platform_id\x18\x04 \x01(\tR\rbotPlatformId\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\"Z\n" +
	"\x18UpdateBotCommandResponse\x12!\n" +
	"\fcommand_name\x18\x01 \x01(\tR\vcommandName\x12\x1b\n" +
	"\tinfo_text\x18\x02 \x01(\tR\binfoText\"?\n" +
	"\x1aGetGlobalBotCommandRequest\x12!\n" +
	"\fcommand_name\x18\x01 \x01(\tR\vcommandName\"^\n" +
	"\x1bGetGlobalBotCommandResponse\x12?\n" +
	"\acommand\x18\x01 \x01(\v2%.senchabot.grpc.botcommand.BotCommandR\acommand\"\x81\x01\n" +
	"\x18GetUserBotCommandRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12&\n" +
	"\x0fbot_platform_id\x18\x03 \x01(\tR\rbotPlatformId\"\\\n" +
	"\x19GetUserBotCommandResponse\x12?\n" +
	"\acommand\x18\x01 \x01(\v2%.senchabot.grpc.botcommand.BotCommandR\acommand\"[\n" +
	"\x15GetCommandListRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12&\n" +
	"\x0fbot_platform_id\x18\x02 \x01(\tR\rbotPlatformId\"[\n" +
	"\x16GetCommandListResponse\x12A\n" +
	"\bcommands\x18\x01 \x03(\v2%.senchabot.grpc.botcommand.BotCommandR\bcommands\"\x80\x01\n" +
	"\x17DeleteBotCommandRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12&\n" +
	"\x0fbot_platform_id\x18\x03 \x01(\tR\rbotPlatformId\"Z\n" +
	"\x18DeleteBotCommandResponse\x12!\n" +
	"\fcommand_name\x18\x01 \x01(\tR\vcommandName\x12\x1b\n" +
	"\tinfo_text\x18\x02 \x01(\tR\binfoText\"\x81\x01\n" +
	"\x16GetCommandAliasRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12#\n" +
	"\rcommand_alias\x18\x02 \x01(\tR\fcommandAlias\x12&\n" +
	"\x0fbot_platform_id\x18\x03 \x01(\tR\rbotPlatformId\"<\n" +
	"\x17GetCommandAliasResponse\x12!\n" +
	"\fcommand_name\x18\x01 \x01(\tR\vcommandName\"\xbb\x01\n" +
	"\x19CreateCommandAliasRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12&\n" +
	"\x0fbot_platform_id\x18\x04 \x01(\tR\rbotPlatformId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\"9\n" +
	"\x1aCreateCommandAliasResponse\x12\x1b\n" +
	"\tinfo_text\x18\x01 \x01(\tR\binfoText\"\x84\x01\n" +
	"\x19DeleteCommandAliasRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12#\n" +
	"\rcommand_alias\x18\x02 \x01(\tR\fcommandAlias\x12&\n" +
	"\x0fbot_platform_id\x18\x03 \x01(\tR\rbotPlatformId\"9\n" +
	"\x1aDeleteCommandAliasResponse\x12\x1b\n" +
	"\tinfo_text\x18\x01 \x01(\tR\binfoText2\x8a\t\n" +
	"\x11BotCommandService\x12{\n" +
	"\x10CreateBotCommand\x122.senchabot.grpc.botcommand.CreateBotCommandRequest\x1a3.senchabot.grpc.botcommand.CreateBotCommandResponse\x12{\n" +
	"\x10UpdateBotCommand\x122.senchabot.grpc.botcommand.UpdateBotCommandRequest\x1a3.senchabot.grpc.botcommand.UpdateBotCommandResponse\x12\x84\x01\n" +
	"\x13GetGlobalBotCommand\x125.senchabot.grpc.botcommand.GetGlobalBotCommandRequest\x1a6.senchabot.grpc.botcommand.GetGlobalBotCommandResponse\x12~\n" +
	"\x11GetUserBotCommand\x123.senchabot.grpc.botcommand.GetUserBotCommandRequest\x1a4.senchabot.grpc.botcommand.GetUserBotCommandResponse\x12u\n" +
	"\x0eGetCommandList\x120.senchabot.grpc.botcommand.GetCommandListRequest\x1a1.senchabot.grpc.botcommand.GetCommandListResponse\x12{\n" +
	"\x10DeleteBotCommand\x122.senchabot.grpc.botcommand.DeleteBotCommandRequest\x1a3.senchabot.grpc.botcommand.DeleteBotCommandResponse\x12x\n" +
	"\x0fGetCommandAlias\x121.senchabot.grpc.botcommand.GetCommandAliasRequest\x1a2.senchabot.grpc.botcommand.GetCommandAliasResponse\x12\x81\x01\n" +
	"\x12CreateCommandAlias\x124.senchabot.grpc.botcommand.CreateCommandAliasRequest\x1a5.senchabot.grpc.botcommand.CreateCommandAliasResponse\x12\x81\x01\n" +
	"\x12DeleteCommandAlias\x124.senchabot.grpc.botcommand.DeleteCommandAliasRequest\x1a5.senchabot.grpc.botcommand.DeleteCommandAliasResponseB:Z8github.com/senchabot-opensource/monorepo/grpc/botcommandb\x06proto3"

var (
	file_botcommand_proto_rawDescOnce sync.Once
	file_botcommand_proto_rawDescData []byte
)

func file_botcommand_proto_rawDescGZIP() []byte {
	file_botcommand_proto_rawDescOnce.Do(func() {
		file_botcommand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_botcommand_proto_rawDesc), len(file_botcommand_proto_rawDesc)))
	})
	return file_botcommand_proto_rawDescData
}

var file_botcommand_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_botcommand_proto_goTypes = []any{
	(*BotCommand)(nil),                  // 0: senchabot.grpc.botcommand.BotCommand
	(*CreateBotCommandRequest)(nil),     // 1: senchabot.grpc.botcommand.CreateBotCommandRequest
	(*CreateBotCommandResponse)(nil),    // 2: senchabot.grpc.botcommand.CreateBotCommandResponse
	(*UpdateBotCommandRequest)(nil),     // 3: senchabot.grpc.botcommand.UpdateBotCommandRequest
	(*UpdateBotCommandResponse)(nil),    // 4: senchabot.grpc.botcommand.UpdateBotCommandResponse
	(*GetGlobalBotCommandRequest)(nil),  // 5: senchabot.grpc.botcommand.GetGlobalBotCommandRequest
	(*GetGlobalBotCommandResponse)(nil), // 6: senchabot.grpc.botcommand.GetGlobalBotCommandResponse
	(*GetUserBotCommandRequest)(nil),    // 7: senchabot.grpc.botcommand.GetUserBotCommandRequest
	(*GetUserBotCommandResponse)(nil),   // 8: senchabot.grpc.botcommand.GetUserBotCommandResponse
	(*GetCommandListRequest)(nil),       // 9: senchabot.grpc.botcommand.GetCommandListRequest
	(*GetCommandListResponse)(nil),      // 10: senchabot.grpc.botcommand.GetCommandListResponse
	(*DeleteBotCommandRequest)(nil),     // 11: senchabot.grpc.botcommand.DeleteBotCommandRequest
	(*DeleteBotCommandResponse)(nil),    // 12: senchabot.grpc.botcommand.DeleteBotCommandResponse
	(*GetCommandAliasRequest)(nil),      // 13: senchabot.grpc.botcommand.GetCommandAliasRequest
	(*GetCommandAliasResponse)(nil),     // 14: senchabot.grpc.botcommand.GetCommandAliasResponse
	(*CreateCommandAliasRequest)(nil),   // 15: senchabot.grpc.botcommand.CreateCommandAliasRequest
	(*CreateCommandAliasResponse)(nil),  // 16: senchabot.grpc.botcommand.CreateCommandAliasResponse
	(*DeleteCommandAliasRequest)(nil),   // 17: senchabot.grpc.botcommand.DeleteCommandAliasRequest
	(*DeleteCommandAliasResponse)(nil),  // 18: senchabot.grpc.botcommand.DeleteCommandAliasResponse
}
var file_botcommand_proto_depIdxs = []int32{
	0,  // 0: senchabot.grpc.botcommand.GetGlobalBotCommandResponse.command:type_name -> senchabot.grpc.botcommand.BotCommand
	0,  // 1: senchabot.grpc.botcommand.GetUserBotCommandResponse.command:type_name -> senchabot.grpc.botcommand.BotCommand
	0,  // 2: senchabot.grpc.botcommand.GetCommandListResponse.commands:type_name -> senchabot.grpc.botcommand.BotCommand
	1,  // 3: senchabot.grpc.botcommand.BotCommandService.CreateBotCommand:input_type -> senchabot.grpc.botcommand.CreateBotCommandRequest
	3,  // 4: senchabot.grpc.botcommand.BotCommandService.UpdateBotCommand:input_type -> senchabot.grpc.botcommand.UpdateBotCommandRequest
	5,  // 5: senchabot.grpc.botcommand.BotCommandService.GetGlobalBotCommand:input_type -> senchabot.grpc.botcommand.GetGlobalBotCommandRequest
	7,  // 6: senchabot.grpc.botcommand.BotCommandService.GetUserBotCommand:input_type -> senchabot.grpc.botcommand.GetUserBotCommandRequest
	9,  // 7: senchabot.grpc.botcommand.BotCommandService.GetCommandList:input_type -> senchabot.grpc.botcommand.GetCommandListRequest
	11, // 8: senchabot.grpc.botcommand.BotCommandService.DeleteBotCommand:input_type -> senchabot.grpc.botcommand.DeleteBotCommandRequest
	13, // 9: senchabot.grpc.botcommand.BotCommandService.GetCommandAlias:input_type -> senchabot.grpc.botcommand.GetCommandAliasRequest
	15, // 10: senchabot.grpc.botcommand.BotCommandService.CreateCommandAlias:input_type -> senchabot.grpc.botcommand.CreateCommandAliasRequest
	17, // 11: senchabot.grpc.botcommand.BotCommandService.DeleteCommandAlias:input_type -> senchabot.grpc.botcommand.DeleteCommandAliasRequest
	2,  // 12: senchabot.grpc.botcommand.BotCommandService.CreateBotCommand:output_type -> senchabot.grpc.botcommand.CreateBotCommandResponse
	4,  // 13: senchabot.grpc.botcommand.BotCommandService.UpdateBotCommand:output_type -> senchabot.grpc.botcommand.UpdateBotCommandResponse
	6,  // 14: senchabot.grpc.botcommand.BotCommandService.GetGlobalBotCommand:output_type -> senchabot.grpc.botcommand.GetGlobalBotCommandResponse
	8,  // 15: senchabot.grpc.botcommand.BotCommandService.GetUserBotCommand:output_type -> senchabot.grpc.botcommand.GetUserBotCommandResponse
	10, // 16: senchabot.grpc.botcommand.BotCommandService.GetCommandList:output_type -> senchabot.grpc.botcommand.GetCommandListResponse
	12, // 17: senchabot.grpc.botcommand.BotCommandService.DeleteBotCommand:output_type -> senchabot.grpc.botcommand.DeleteBotCommandResponse
	14, // 18: senchabot.grpc.botcommand.BotCommandService.GetCommandAlias:output_type -> senchabot.grpc.botcommand.GetCommandAliasResponse
	16, // 19: senchabot.grpc.botcommand.BotCommandService.CreateCommandAlias:output_type -> senchabot.grpc.botcommand.CreateCommandAliasResponse
	18, // 20: senchabot.grpc.botcommand.BotCommandService.DeleteCommandAlias:output_type -> senchabot.grpc.botcommand.DeleteCommandAliasResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_botcommand_proto_init() }
func file_botcommand_proto_init() {
	if File_botcommand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_botcommand_proto_rawDesc), len(file_botcommand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_botcommand_proto_goTypes,
		DependencyIndexes: file_botcommand_proto_depIdxs,
		MessageInfos:      file_botcommand_proto_msgTypes,
	}.Build()
	File_botcommand_proto = out.File
	file_botcommand_proto_goTypes = nil
	file_botcommand_proto_depIdxs = nil
}
