// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: botcommand.proto

package botcommand

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotCommandService_CreateBotCommand_FullMethodName    = "/senchabot.grpc.botcommand.BotCommandService/CreateBotCommand"
	BotCommandService_UpdateBotCommand_FullMethodName    = "/senchabot.grpc.botcommand.BotCommandService/UpdateBotCommand"
	BotCommandService_GetGlobalBotCommand_FullMethodName = "/senchabot.grpc.botcommand.BotCommandService/GetGlobalBotCommand"
	BotCommandService_GetUserBotCommand_FullMethodName   = "/senchabot.grpc.botcommand.BotCommandService/GetUserBotCommand"
	BotCommandService_GetCommandList_FullMethodName      = "/senchabot.grpc.botcommand.BotCommandService/GetCommandList"
	BotCommandService_DeleteBotCommand_FullMethodName    = "/senchabot.grpc.botcommand.BotCommandService/DeleteBotCommand"
	BotCommandService_GetCommandAlias_FullMethodName     = "/senchabot.grpc.botcommand.BotCommandService/GetCommandAlias"
	BotCommandService_CreateCommandAlias_FullMethodName  = "/senchabot.grpc.botcommand.BotCommandService/CreateCommandAlias"
	BotCommandService_DeleteCommandAlias_FullMethodName  = "/senchabot.grpc.botcommand.BotCommandService/DeleteCommandAlias"
)

// BotCommandServiceClient is the client API for BotCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotCommandServiceClient interface {
	CreateBotCommand(ctx context.Context, in *CreateBotCommandRequest, opts ...grpc.CallOption) (*CreateBotCommandResponse, error)
	UpdateBotCommand(ctx context.Context, in *UpdateBotCommandRequest, opts ...grpc.CallOption) (*UpdateBotCommandResponse, error)
	GetGlobalBotCommand(ctx context.Context, in *GetGlobalBotCommandRequest, opts ...grpc.CallOption) (*GetGlobalBotCommandResponse, error)
	GetUserBotCommand(ctx context.Context, in *GetUserBotCommandRequest, opts ...grpc.CallOption) (*GetUserBotCommandResponse, error)
	GetCommandList(ctx context.Context, in *GetCommandListRequest, opts ...grpc.CallOption) (*GetCommandListResponse, error)
	DeleteBotCommand(ctx context.Context, in *DeleteBotCommandRequest, opts ...grpc.CallOption) (*DeleteBotCommandResponse, error)
	GetCommandAlias(ctx context.Context, in *GetCommandAliasRequest, opts ...grpc.CallOption) (*GetCommandAliasResponse, error)
	CreateCommandAlias(ctx context.Context, in *CreateCommandAliasRequest, opts ...grpc.CallOption) (*CreateCommandAliasResponse, error)
	DeleteCommandAlias(ctx context.Context, in *DeleteCommandAliasRequest, opts ...grpc.CallOption) (*DeleteCommandAliasResponse, error)
}

type botCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotCommandServiceClient(cc grpc.ClientConnInterface) BotCommandServiceClient {
	return &botCommandServiceClient{cc}
}

func (c *botCommandServiceClient) CreateBotCommand(ctx context.Context, in *CreateBotCommandRequest, opts ...grpc.CallOption) (*CreateBotCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBotCommandResponse)
	err := c.cc.Invoke(ctx, BotCommandService_CreateBotCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) UpdateBotCommand(ctx context.Context, in *UpdateBotCommandRequest, opts ...grpc.CallOption) (*UpdateBotCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBotCommandResponse)
	err := c.cc.Invoke(ctx, BotCommandService_UpdateBotCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) GetGlobalBotCommand(ctx context.Context, in *GetGlobalBotCommandRequest, opts ...grpc.CallOption) (*GetGlobalBotCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalBotCommandResponse)
	err := c.cc.Invoke(ctx, BotCommandService_GetGlobalBotCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) GetUserBotCommand(ctx context.Context, in *GetUserBotCommandRequest, opts ...grpc.CallOption) (*GetUserBotCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBotCommandResponse)
	err := c.cc.Invoke(ctx, BotCommandService_GetUserBotCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) GetCommandList(ctx context.Context, in *GetCommandListRequest, opts ...grpc.CallOption) (*GetCommandListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandListResponse)
	err := c.cc.Invoke(ctx, BotCommandService_GetCommandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) DeleteBotCommand(ctx context.Context, in *DeleteBotCommandRequest, opts ...grpc.CallOption) (*DeleteBotCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBotCommandResponse)
	err := c.cc.Invoke(ctx, BotCommandService_DeleteBotCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) GetCommandAlias(ctx context.Context, in *GetCommandAliasRequest, opts ...grpc.CallOption) (*GetCommandAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandAliasResponse)
	err := c.cc.Invoke(ctx, BotCommandService_GetCommandAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) CreateCommandAlias(ctx context.Context, in *CreateCommandAliasRequest, opts ...grpc.CallOption) (*CreateCommandAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommandAliasResponse)
	err := c.cc.Invoke(ctx, BotCommandService_CreateCommandAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botCommandServiceClient) DeleteCommandAlias(ctx context.Context, in *DeleteCommandAliasRequest, opts ...grpc.CallOption) (*DeleteCommandAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommandAliasResponse)
	err := c.cc.Invoke(ctx, BotCommandService_DeleteCommandAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotCommandServiceServer is the server API for BotCommandService service.
// All implementations must embed UnimplementedBotCommandServiceServer
// for forward compatibility.
type BotCommandServiceServer interface {
	CreateBotCommand(context.Context, *CreateBotCommandRequest) (*CreateBotCommandResponse, error)
	UpdateBotCommand(context.Context, *UpdateBotCommandRequest) (*UpdateBotCommandResponse, error)
	GetGlobalBotCommand(context.Context, *GetGlobalBotCommandRequest) (*GetGlobalBotCommandResponse, error)
	GetUserBotCommand(context.Context, *GetUserBotCommandRequest) (*GetUserBotCommandResponse, error)
	GetCommandList(context.Context, *GetCommandListRequest) (*GetCommandListResponse, error)
	DeleteBotCommand(context.Context, *DeleteBotCommandRequest) (*DeleteBotCommandResponse, error)
	GetCommandAlias(context.Context, *GetCommandAliasRequest) (*GetCommandAliasResponse, error)
	CreateCommandAlias(context.Context, *CreateCommandAliasRequest) (*CreateCommandAliasResponse, error)
	DeleteCommandAlias(context.Context, *DeleteCommandAliasRequest) (*DeleteCommandAliasResponse, error)
	mustEmbedUnimplementedBotCommandServiceServer()
}

// UnimplementedBotCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotCommandServiceServer struct{}

func (UnimplementedBotCommandServiceServer) CreateBotCommand(context.Context, *CreateBotCommandRequest) (*CreateBotCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBotCommand not implemented")
}
func (UnimplementedBotCommandServiceServer) UpdateBotCommand(context.Context, *UpdateBotCommandRequest) (*UpdateBotCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBotCommand not implemented")
}
func (UnimplementedBotCommandServiceServer) GetGlobalBotCommand(context.Context, *GetGlobalBotCommandRequest) (*GetGlobalBotCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalBotCommand not implemented")
}
func (UnimplementedBotCommandServiceServer) GetUserBotCommand(context.Context, *GetUserBotCommandRequest) (*GetUserBotCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBotCommand not implemented")
}
func (UnimplementedBotCommandServiceServer) GetCommandList(context.Context, *GetCommandListRequest) (*GetCommandListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommandList not implemented")
}
func (UnimplementedBotCommandServiceServer) DeleteBotCommand(context.Context, *DeleteBotCommandRequest) (*DeleteBotCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBotCommand not implemented")
}
func (UnimplementedBotCommandServiceServer) GetCommandAlias(context.Context, *GetCommandAliasRequest) (*GetCommandAliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommandAlias not implemented")
}
func (UnimplementedBotCommandServiceServer) CreateCommandAlias(context.Context, *CreateCommandAliasRequest) (*CreateCommandAliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommandAlias not implemented")
}
func (UnimplementedBotCommandServiceServer) DeleteCommandAlias(context.Context, *DeleteCommandAliasRequest) (*DeleteCommandAliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCommandAlias not implemented")
}
func (UnimplementedBotCommandServiceServer) mustEmbedUnimplementedBotCommandServiceServer() {}
func (UnimplementedBotCommandServiceServer) testEmbeddedByValue()                           {}

// UnsafeBotCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotCommandServiceServer will
// result in compilation errors.
type UnsafeBotCommandServiceServer interface {
	mustEmbedUnimplementedBotCommandServiceServer()
}

func RegisterBotCommandServiceServer(s grpc.ServiceRegistrar, srv BotCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedBotCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotCommandService_ServiceDesc, srv)
}

func _BotCommandService_CreateBotCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).CreateBotCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_CreateBotCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).CreateBotCommand(ctx, req.(*CreateBotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_UpdateBotCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).UpdateBotCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_UpdateBotCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).UpdateBotCommand(ctx, req.(*UpdateBotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_GetGlobalBotCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalBotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).GetGlobalBotCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_GetGlobalBotCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).GetGlobalBotCommand(ctx, req.(*GetGlobalBotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_GetUserBotCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).GetUserBotCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_GetUserBotCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).GetUserBotCommand(ctx, req.(*GetUserBotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_GetCommandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).GetCommandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_GetCommandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).GetCommandList(ctx, req.(*GetCommandListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_DeleteBotCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).DeleteBotCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_DeleteBotCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).DeleteBotCommand(ctx, req.(*DeleteBotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_GetCommandAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).GetCommandAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_GetCommandAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).GetCommandAlias(ctx, req.(*GetCommandAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_CreateCommandAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommandAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).CreateCommandAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_CreateCommandAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).CreateCommandAlias(ctx, req.(*CreateCommandAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotCommandService_DeleteCommandAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommandAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotCommandServiceServer).DeleteCommandAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotCommandService_DeleteCommandAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotCommandServiceServer).DeleteCommandAlias(ctx, req.(*DeleteCommandAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotCommandService_ServiceDesc is the grpc.ServiceDesc for BotCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "senchabot.grpc.botcommand.BotCommandService",
	HandlerType: (*BotCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBotCommand",
			Handler:    _BotCommandService_CreateBotCommand_Handler,
		},
		{
			MethodName: "UpdateBotCommand",
			Handler:    _BotCommandService_UpdateBotCommand_Handler,
		},
		{
			MethodName: "GetGlobalBotCommand",
			Handler:    _BotCommandService_GetGlobalBotCommand_Handler,
		},
		{
			MethodName: "GetUserBotCommand",
			Handler:    _BotCommandService_GetUserBotCommand_Handler,
		},
		{
			MethodName: "GetCommandList",
			Handler:    _BotCommandService_GetCommandList_Handler,
		},
		{
			MethodName: "DeleteBotCommand",
			Handler:    _BotCommandService_DeleteBotCommand_Handler,
		},
		{
			MethodName: "GetCommandAlias",
			Handler:    _BotCommandService_GetCommandAlias_Handler,
		},
		{
			MethodName: "CreateCommandAlias",
			Handler:    _BotCommandService_CreateCommandAlias_Handler,
		},
		{
			MethodName: "DeleteCommandAlias",
			Handler:    _BotCommandService_DeleteCommandAlias_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "botcommand.proto",
}
