/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetsSubSproutWidgetRouteImport } from './routes/widgets/sub-sprout-widget'
import { Route as WidgetsRaffleOverlayRouteImport } from './routes/widgets/raffle-overlay'
import { Route as WidgetsChatWidgetRouteImport } from './routes/widgets/chat-widget'
import { Route as WidgetsAlertsRouteImport } from './routes/widgets/alerts'
import { Route as SetupSubGrowingPlantRouteImport } from './routes/setup/sub-growing-plant'
import { Route as SetupRaffleRouteImport } from './routes/setup/raffle'
import { Route as SetupChatWidgetRouteImport } from './routes/setup/chat-widget'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsSubSproutWidgetRoute = WidgetsSubSproutWidgetRouteImport.update({
  id: '/widgets/sub-sprout-widget',
  path: '/widgets/sub-sprout-widget',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsRaffleOverlayRoute = WidgetsRaffleOverlayRouteImport.update({
  id: '/widgets/raffle-overlay',
  path: '/widgets/raffle-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsChatWidgetRoute = WidgetsChatWidgetRouteImport.update({
  id: '/widgets/chat-widget',
  path: '/widgets/chat-widget',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsAlertsRoute = WidgetsAlertsRouteImport.update({
  id: '/widgets/alerts',
  path: '/widgets/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSubGrowingPlantRoute = SetupSubGrowingPlantRouteImport.update({
  id: '/setup/sub-growing-plant',
  path: '/setup/sub-growing-plant',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRaffleRoute = SetupRaffleRouteImport.update({
  id: '/setup/raffle',
  path: '/setup/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupChatWidgetRoute = SetupChatWidgetRouteImport.update({
  id: '/setup/chat-widget',
  path: '/setup/chat-widget',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup/chat-widget': typeof SetupChatWidgetRoute
  '/setup/raffle': typeof SetupRaffleRoute
  '/setup/sub-growing-plant': typeof SetupSubGrowingPlantRoute
  '/widgets/alerts': typeof WidgetsAlertsRoute
  '/widgets/chat-widget': typeof WidgetsChatWidgetRoute
  '/widgets/raffle-overlay': typeof WidgetsRaffleOverlayRoute
  '/widgets/sub-sprout-widget': typeof WidgetsSubSproutWidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup/chat-widget': typeof SetupChatWidgetRoute
  '/setup/raffle': typeof SetupRaffleRoute
  '/setup/sub-growing-plant': typeof SetupSubGrowingPlantRoute
  '/widgets/alerts': typeof WidgetsAlertsRoute
  '/widgets/chat-widget': typeof WidgetsChatWidgetRoute
  '/widgets/raffle-overlay': typeof WidgetsRaffleOverlayRoute
  '/widgets/sub-sprout-widget': typeof WidgetsSubSproutWidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setup/chat-widget': typeof SetupChatWidgetRoute
  '/setup/raffle': typeof SetupRaffleRoute
  '/setup/sub-growing-plant': typeof SetupSubGrowingPlantRoute
  '/widgets/alerts': typeof WidgetsAlertsRoute
  '/widgets/chat-widget': typeof WidgetsChatWidgetRoute
  '/widgets/raffle-overlay': typeof WidgetsRaffleOverlayRoute
  '/widgets/sub-sprout-widget': typeof WidgetsSubSproutWidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup/chat-widget'
    | '/setup/raffle'
    | '/setup/sub-growing-plant'
    | '/widgets/alerts'
    | '/widgets/chat-widget'
    | '/widgets/raffle-overlay'
    | '/widgets/sub-sprout-widget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup/chat-widget'
    | '/setup/raffle'
    | '/setup/sub-growing-plant'
    | '/widgets/alerts'
    | '/widgets/chat-widget'
    | '/widgets/raffle-overlay'
    | '/widgets/sub-sprout-widget'
  id:
    | '__root__'
    | '/'
    | '/setup/chat-widget'
    | '/setup/raffle'
    | '/setup/sub-growing-plant'
    | '/widgets/alerts'
    | '/widgets/chat-widget'
    | '/widgets/raffle-overlay'
    | '/widgets/sub-sprout-widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupChatWidgetRoute: typeof SetupChatWidgetRoute
  SetupRaffleRoute: typeof SetupRaffleRoute
  SetupSubGrowingPlantRoute: typeof SetupSubGrowingPlantRoute
  WidgetsAlertsRoute: typeof WidgetsAlertsRoute
  WidgetsChatWidgetRoute: typeof WidgetsChatWidgetRoute
  WidgetsRaffleOverlayRoute: typeof WidgetsRaffleOverlayRoute
  WidgetsSubSproutWidgetRoute: typeof WidgetsSubSproutWidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/sub-sprout-widget': {
      id: '/widgets/sub-sprout-widget'
      path: '/widgets/sub-sprout-widget'
      fullPath: '/widgets/sub-sprout-widget'
      preLoaderRoute: typeof WidgetsSubSproutWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/raffle-overlay': {
      id: '/widgets/raffle-overlay'
      path: '/widgets/raffle-overlay'
      fullPath: '/widgets/raffle-overlay'
      preLoaderRoute: typeof WidgetsRaffleOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/chat-widget': {
      id: '/widgets/chat-widget'
      path: '/widgets/chat-widget'
      fullPath: '/widgets/chat-widget'
      preLoaderRoute: typeof WidgetsChatWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/alerts': {
      id: '/widgets/alerts'
      path: '/widgets/alerts'
      fullPath: '/widgets/alerts'
      preLoaderRoute: typeof WidgetsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/sub-growing-plant': {
      id: '/setup/sub-growing-plant'
      path: '/setup/sub-growing-plant'
      fullPath: '/setup/sub-growing-plant'
      preLoaderRoute: typeof SetupSubGrowingPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/raffle': {
      id: '/setup/raffle'
      path: '/setup/raffle'
      fullPath: '/setup/raffle'
      preLoaderRoute: typeof SetupRaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/chat-widget': {
      id: '/setup/chat-widget'
      path: '/setup/chat-widget'
      fullPath: '/setup/chat-widget'
      preLoaderRoute: typeof SetupChatWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupChatWidgetRoute: SetupChatWidgetRoute,
  SetupRaffleRoute: SetupRaffleRoute,
  SetupSubGrowingPlantRoute: SetupSubGrowingPlantRoute,
  WidgetsAlertsRoute: WidgetsAlertsRoute,
  WidgetsChatWidgetRoute: WidgetsChatWidgetRoute,
  WidgetsRaffleOverlayRoute: WidgetsRaffleOverlayRoute,
  WidgetsSubSproutWidgetRoute: WidgetsSubSproutWidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
