# fly.toml app configuration file generated for senchabotdctest on 2023-08-03T14:56:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "senchabotdctest"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
