import type { PresetData } from './preset-schema';

const SENCHABOT = { name: 'Senchabot', url: 'https://senchabot.com' };

// Fan-made looks: palettes and free Google Fonts only, no game logos, art or fonts. Every
// font here has latin-ext, so Turkish letters (ş ğ ı İ) keep the preset's font.
export const BUILTIN_PRESETS: readonly PresetData[] = [
  {
    id: 'rift',
    name: 'Rift',
    game: 'League of Legends',
    author: SENCHABOT,
    fonts: {
      display: { family: 'Cinzel', weights: '400..900', fallback: 'serif' },
      body: { family: 'Nunito Sans', weights: '400..800', fallback: 'sans-serif' },
    },
    colors: {
      accent: '#0ac8b9',
      win: '#c8aa6e',
      text: '#f0e6d2',
      muted: '#a09b8c',
      panel: '#0a1428',
      panel2: '#010a13',
      frame: '#c8aa6e',
      frame2: '#785a28',
      track: '#1e2328',
    },
    panelOpacity: 0.92,
    frame: 'gilded',
    radius: 0,
    skew: 0,
    title: { upper: true, italic: false, tracking: 0.12 },
    fill: 'gloss',
    motion: 'unfold',
    sound: 'celestial',
    shadow: 'soft',
  },
  {
    id: 'realm',
    name: 'Realm',
    game: 'World of Warcraft',
    author: SENCHABOT,
    fonts: {
      display: { family: 'Marcellus', weights: '400', fallback: 'serif' },
      body: { family: 'Alegreya Sans', weights: '400;500;700;800', fallback: 'sans-serif' },
    },
    colors: {
      accent: '#ff8000',
      win: '#ffd100',
      text: '#fff4d6',
      muted: '#bfae8a',
      panel: '#2a1d12',
      panel2: '#120c07',
      frame: '#e0b252',
      frame2: '#6b4a1c',
      track: '#0d0906',
    },
    panelOpacity: 0.93,
    frame: 'ornate',
    radius: 0.6,
    skew: 0,
    title: { upper: false, italic: false, tracking: 0.04 },
    fill: 'gloss',
    motion: 'drop',
    sound: 'celestial',
    shadow: 'soft',
  },
  {
    id: 'dynasty',
    name: 'Dynasty',
    game: 'Metin2',
    author: SENCHABOT,
    fonts: {
      display: { family: 'Zen Antique', weights: '400', fallback: 'serif' },
      body: { family: 'Noto Serif', weights: '400..700', fallback: 'serif' },
    },
    colors: {
      accent: '#d23a2e',
      win: '#e8c15a',
      text: '#f5e9d0',
      muted: '#b9a582',
      panel: '#3a1712',
      panel2: '#170806',
      frame: '#d9ad4c',
      frame2: '#7a1a14',
      track: '#120605',
    },
    panelOpacity: 0.93,
    frame: 'lacquer',
    radius: 0.3,
    skew: 0,
    title: { upper: false, italic: false, tracking: 0.08 },
    fill: 'gloss',
    motion: 'scroll',
    sound: 'celestial',
    shadow: 'soft',
  },
  {
    id: 'ancient',
    name: 'Ancient',
    game: 'Dota 2',
    author: SENCHABOT,
    fonts: {
      display: { family: 'Grenze', weights: '400..900', fallback: 'serif' },
      body: { family: 'Barlow', weights: '400;500;600;700;800', fallback: 'sans-serif' },
    },
    colors: {
      accent: '#c23c2a',
      win: '#d8b55b',
      text: '#e8e4dc',
      muted: '#8f9398',
      panel: '#1b1f23',
      panel2: '#0b0d0f',
      frame: '#9c7a3c',
      frame2: '#3b4148',
      track: '#070809',
    },
    panelOpacity: 0.94,
    frame: 'iron',
    radius: 0.2,
    skew: 0,
    title: { upper: true, italic: false, tracking: 0.08 },
    fill: 'gloss',
    motion: 'slam',
    sound: 'celestial',
    shadow: 'soft',
  },
  {
    id: 'agent',
    name: 'Agent',
    game: 'Valorant',
    author: SENCHABOT,
    fonts: {
      display: { family: 'Teko', weights: '400..700', fallback: 'sans-serif' },
      body: { family: 'Barlow', weights: '400;500;600;700;800', fallback: 'sans-serif' },
    },
    colors: {
      accent: '#ff4655',
      win: '#2ee6b8',
      text: '#ece8e1',
      muted: '#8b978f',
      panel: '#1f2731',
      panel2: '#0f1923',
      frame: '#ece8e1',
      frame2: '#3a4654',
      track: '#0a1016',
    },
    panelOpacity: 0.94,
    frame: 'tactical',
    radius: 0,
    skew: -10,
    title: { upper: true, italic: false, tracking: 0.06 },
    fill: 'flat',
    motion: 'slide',
    sound: 'neon',
    shadow: 'soft',
  },
  {
    id: 'defuse',
    name: 'Defuse',
    game: 'Counter-Strike 2',
    author: SENCHABOT,
    fonts: {
      display: {
        family: 'Saira Condensed',
        weights: '400;500;600;700;800',
        fallback: 'sans-serif',
      },
      body: { family: 'Saira', weights: '400..800', fallback: 'sans-serif' },
    },
    colors: {
      accent: '#de9b35',
      win: '#6f9bd8',
      text: '#e6e6e6',
      muted: '#9aa3ad',
      panel: '#20262e',
      panel2: '#12161b',
      frame: '#c9d1d9',
      frame2: '#39424d',
      track: '#0b0e11',
    },
    panelOpacity: 0.94,
    frame: 'hud',
    radius: 0.15,
    skew: 0,
    title: { upper: true, italic: false, tracking: 0.1 },
    fill: 'stripes',
    motion: 'wipe',
    sound: 'neon',
    shadow: 'soft',
  },
  {
    id: 'blocks',
    name: 'Blocks',
    game: 'Minecraft',
    author: SENCHABOT,
    fonts: {
      // Pixelify Sans was tried first: its 5 reads as an S.
      display: { family: 'Jersey 10', weights: '400', fallback: 'monospace' },
      body: { family: 'Jersey 10', weights: '400', fallback: 'monospace' },
    },
    colors: {
      accent: '#80ff20',
      win: '#ffaa00',
      text: '#ffffff',
      muted: '#aaaaaa',
      panel: '#100010',
      panel2: '#100010',
      frame: '#3b16b0',
      frame2: '#1d0858',
      track: '#1c1c1c',
    },
    panelOpacity: 0.94,
    frame: 'pixel',
    radius: 0,
    skew: 0,
    title: { upper: false, italic: false, tracking: 0.02 },
    fill: 'blocks',
    motion: 'pop',
    sound: 'neon',
    shadow: 'hard',
  },
];
