FROM golang:1.24-alpine

WORKDIR /app

# Install CA certificates
RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", "./apps/twitch-bot/.air.toml"]