/**
 * Writes the widget URL golden fixtures (src/__tests__/url-contract/fixtures/*.json) by running the
 * frozen pre-redesign logic in base-reference.ts over a bounded input matrix per widget.
 *
 *   node scripts/url-contract/generate.ts
 *
 * Deterministic: rerunning it must leave the fixtures byte-identical. See README.md.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as BASE from './base-reference.ts';

const ORIGIN = 'https://extensions.senchabot.com';
const APP_DIR = fileURLToPath(new URL('../../', import.meta.url));
const OUT_DIR = `${APP_DIR}src/__tests__/url-contract/fixtures`;
const ABOUT =
  'Generated by scripts/url-contract/generate.ts from the frozen pre-redesign URL logic ' +
  '(scripts/url-contract/base-reference.ts). Do not edit by hand.';

type Row = Record<string, unknown>;
type Domain = Record<string, readonly unknown[]>;

/**
 * Greedy all-pairs covering array: every value of every parameter meets every value of every
 * other parameter in at least one row. Ties pick the lowest index, so output is deterministic
 * and leans towards the first (default) value.
 */
function allPairs(domain: Domain): Row[] {
  const keys = Object.keys(domain);
  const sizes = keys.map((k) => domain[k].length);
  const id = (i: number, a: number, j: number, b: number) =>
    i < j ? `${i}:${a}|${j}:${b}` : `${j}:${b}|${i}:${a}`;
  const uncovered = new Set<string>();
  for (let i = 0; i < keys.length; i++)
    for (let j = i + 1; j < keys.length; j++)
      for (let a = 0; a < sizes[i]; a++)
        for (let b = 0; b < sizes[j]; b++) uncovered.add(id(i, a, j, b));

  const rows: number[][] = [];
  while (uncovered.size > 0) {
    const [first] = uncovered;
    const [[i, a], [j, b]] = first.split('|').map((p) => p.split(':').map(Number));
    const row = keys.map(() => -1);
    row[i] = a;
    row[j] = b;
    for (let k = 0; k < keys.length; k++) {
      if (row[k] !== -1) continue;
      let best = 0;
      let bestGain = -1;
      for (let v = 0; v < sizes[k]; v++) {
        let gain = 0;
        for (let m = 0; m < keys.length; m++) {
          if (m !== k && row[m] !== -1 && uncovered.has(id(k, v, m, row[m]))) gain++;
        }
        if (gain > bestGain) {
          best = v;
          bestGain = gain;
        }
      }
      row[k] = best;
    }
    for (let m = 0; m < keys.length; m++)
      for (let n = m + 1; n < keys.length; n++) uncovered.delete(id(m, row[m], n, row[n]));
    rows.push(row);
  }
  return rows.map((row) => Object.fromEntries(keys.map((k, i) => [k, domain[k][row[i]]])));
}

/** Only the keys whose value differs from the defaults. */
function overrides<T extends object>(value: T, defaults: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(value).filter(
      ([k, v]) => JSON.stringify(v) !== JSON.stringify(defaults[k as keyof T]),
    ),
  ) as Partial<T>;
}

/** Every non-default value of every key, one key at a time. */
function singleChanges<T extends object>(defaults: T, domain: Domain): Partial<T>[] {
  const out: Partial<T>[] = [];
  for (const [key, values] of Object.entries(domain)) {
    for (const value of values) {
      if (JSON.stringify(value) !== JSON.stringify(defaults[key as keyof T])) {
        out.push({ [key]: value } as Partial<T>);
      }
    }
  }
  return out;
}

const bools = (defaults: object, keys: readonly string[]): Domain =>
  Object.fromEntries(
    keys.map((k) => {
      const d = defaults[k as keyof typeof defaults] as boolean;
      return [k, [d, !d]];
    }),
  );

// Both, one, none, uppercase, padded and whitespace-only. Digit-only names are left out: the
// router parses `?twitch=123` as a number, which the widget routes' schemas reject. Pairwise
// rows lean towards the first entry and skip the empty pair, which never builds a URL.
const CHANNELS: readonly [string, string][] = [
  ['foo', 'bar'],
  ['foo', ''],
  ['', 'bar'],
  ['', ''],
  ['  Foo ', ' BAR  '],
  ['FOO', ''],
  ['   ', 'bar'],
  ['foo', '   '],
  ['streamer_01', 'kick-name'],
];
const PAIR_CHANNELS = CHANNELS.filter(([twitch, kick]) => twitch || kick);

interface Fixture {
  about: string;
  origin: string;
  defaults?: unknown;
  cases: { group: string; input: unknown; expectedUrl: string }[];
}

// ---------------------------------------------------------------------------------------------
// Chat Box
// ---------------------------------------------------------------------------------------------

function chatBox(): Fixture {
  const D = BASE.DEFAULT_SETTINGS;
  const domain: Domain = {
    platforms: BASE.PLATFORMS,
    platformDisplay: BASE.PLATFORM_DISPLAYS,
    font: BASE.FONTS,
    fontSize: ['18', '', '8', '72', '0', '100', '24'],
    layout: BASE.LAYOUTS,
    orientation: BASE.ORIENTATIONS,
    animation: BASE.ANIMATIONS,
    bgOpacity: ['0.5', '0', '1', '0.3'],
    duration: BASE.DURATIONS,
    highlights: [
      [...BASE.HIGHLIGHTS],
      [],
      ['mention'],
      ['reply', 'mention'],
      ['firstMessage', 'announcement', 'highlighted'],
    ],
    ...bools(D, [
      'background',
      'itemBackground',
      'platformAccent',
      'boldUsernames',
      'boldMessages',
      'sevenTv',
      'bttv',
      'ffz',
      'badges',
      'timestamp',
      'hideBots',
      'hideCommands',
    ]),
  };
  const cases: Fixture['cases'] = [];
  const add = (group: string, settings: BASE.Settings, [twitch, kick]: readonly string[]) =>
    cases.push({
      group,
      input: { twitchChannel: twitch, kickChannel: kick, settings: overrides(settings, D) },
      expectedUrl: BASE.baseChatBoxUrl(ORIGIN, settings, twitch, kick),
    });

  for (const channels of CHANNELS)
    for (const platforms of BASE.PLATFORMS) add('channels', { ...D, platforms }, channels);
  for (const platforms of BASE.PLATFORMS)
    for (const change of singleChanges(D, { ...domain, platforms: [] }))
      add('single', { ...D, platforms, ...change }, ['foo', 'bar']);
  for (const { channels, ...settings } of allPairs({ channels: PAIR_CHANNELS, ...domain }))
    add('pairwise', { ...D, ...(settings as Partial<BASE.Settings>) }, channels as string[]);
  return { about: ABOUT, origin: ORIGIN, defaults: D, cases };
}

// ---------------------------------------------------------------------------------------------
// Emote Wall
// ---------------------------------------------------------------------------------------------

function emoteWall(): Fixture {
  const D = BASE.DEFAULT_EMOTE_WALL_OPTIONS;
  const domain: Domain = {
    platforms: BASE.PLATFORMS,
    mode: BASE.EMOTE_WALL_MODES,
    ...bools(D, ['sevenTv', 'subsOnly', 'subDurationX2', 'showAllEmotes', 'hypeMode', 'spamBlock']),
    // Default, empty, both bounds, out of range on both sides, a middle value, and text the
    // number fields can't produce but old state or a pasted value could.
    size: ['112', '', '32', '256', '8', '300', '40', '2.5', ' 64 ', '1e2', 'abc', '-5'],
    duration: ['5', '', '2', '30', '0', '99', '7', '2.5', ' 6 '],
    max: ['25', '', '1', '120', '0', '500', '60', '1e2'],
  };
  const cases: Fixture['cases'] = [];
  const add = (group: string, options: BASE.EmoteWallUrlOptions) =>
    cases.push({
      group,
      input: overrides(options, D),
      expectedUrl: BASE.buildEmoteWallUrl(ORIGIN, options),
    });

  for (const [twitch, kick] of CHANNELS)
    for (const platforms of BASE.PLATFORMS) add('channels', { ...D, twitch, kick, platforms });
  for (const platforms of BASE.PLATFORMS)
    for (const change of singleChanges(D, { ...domain, platforms: [] }))
      add('single', { ...D, twitch: 'foo', kick: 'bar', platforms, ...change });
  for (const { channels, ...options } of allPairs({ channels: PAIR_CHANNELS, ...domain })) {
    const [twitch, kick] = channels as string[];
    add('pairwise', { ...D, ...(options as Partial<BASE.EmoteWallUrlOptions>), twitch, kick });
  }
  return { about: ABOUT, origin: ORIGIN, defaults: D, cases };
}

// ---------------------------------------------------------------------------------------------
// Sub Sprout
// ---------------------------------------------------------------------------------------------

function subSprout(): Fixture {
  // Named like the current buildSubSproutUrl settings; `platforms` was `platform` in the page.
  const D = {
    platforms: 'both',
    variety: 'classic',
    pick: 'fixed',
    water: 'off',
    countFx: true,
    potLabel: false,
  } as const;
  type Settings = {
    platforms: BASE.SubSproutState['platform'];
    variety: BASE.SubSproutState['variety'];
    pick: BASE.SubSproutState['pick'];
    water: BASE.SubSproutState['water'];
    countFx: boolean;
    potLabel: boolean;
  };
  const domain: Domain = {
    platforms: BASE.PLATFORMS,
    variety: BASE.PLANT_IDS,
    pick: BASE.PICK_MODES,
    water: BASE.WATER_EFFECTS,
    ...bools(D, ['countFx', 'potLabel']),
  };
  const cases: Fixture['cases'] = [];
  const add = (group: string, settings: Settings, [twitch, kick]: readonly string[]) =>
    cases.push({
      group,
      input: { twitchChannel: twitch, kickChannel: kick, settings: overrides(settings, D) },
      expectedUrl: BASE.baseSubSproutUrl(ORIGIN, {
        ...settings,
        platform: settings.platforms,
        twitchChannel: twitch,
        kickChannel: kick,
      }),
    });

  for (const channels of CHANNELS)
    for (const platforms of BASE.PLATFORMS) add('channels', { ...D, platforms }, channels);
  for (const platforms of BASE.PLATFORMS)
    for (const change of singleChanges<Settings>(D, { ...domain, platforms: [] }))
      add('single', { ...D, platforms, ...change }, ['foo', 'bar']);
  for (const { channels, ...settings } of allPairs({ channels: PAIR_CHANNELS, ...domain }))
    add('pairwise', { ...D, ...(settings as Partial<Settings>) }, channels as string[]);
  return { about: ABOUT, origin: ORIGIN, defaults: D, cases };
}

// ---------------------------------------------------------------------------------------------
// OBS Bridge
// ---------------------------------------------------------------------------------------------

function obsBridge(): Fixture {
  // Only inputs both versions treat alike. The redesign trims and lowercases channels, trims the
  // WebSocket URL and drops blank or default-equivalent commands on purpose; the tests cover those
  // as named rules and assert that no fixture input falls under them.
  const channels: readonly [string, string][] = [
    ['foo', 'bar'],
    ['foo', ''],
    ['', 'bar'],
    ['streamer_01', 'kick-name'],
  ];
  const users: BASE.CommandUser[][] = [
    [],
    [{ platform: 'twitch', name: 'mod1' }],
    [
      { platform: 'twitch', name: 'a' },
      { platform: 'kick', name: 'b' },
    ],
    [{ platform: 'kick', name: 'x:y' }],
    [{ platform: null, name: 'carol' }],
    [
      { platform: 'twitch', name: 'bob' },
      { platform: null, name: 'carol' },
      { platform: 'kick', name: 'ali' },
    ],
  ];
  const wsUrls = ['', 'ws://192.168.1.5:4455', 'ws://localhost:4455/path?x=1&y=2'];
  const passwords = ['', 'p@ss w&rd=1', ' ', ' padded ', 'ünï+/?%#'];
  // undefined: never typed in (the current form starts empty, the old one started on the default).
  const commandValues = (key: BASE.ObsCommandKey) => [
    undefined,
    '',
    BASE.DEFAULT_OBS_COMMANDS[key],
    `x${key}`,
    `  x${key} `,
    `!My${key.slice(3)}`,
    '!szene ç&=',
  ];
  const keys = Object.keys(BASE.DEFAULT_OBS_COMMANDS) as BASE.ObsCommandKey[];

  const cases: Fixture['cases'] = [];
  const add = (
    group: string,
    [twitch, kick]: readonly string[],
    commandUsers: BASE.CommandUser[],
    commands: Partial<Record<BASE.ObsCommandKey, string>>,
    obsWebsocketUrl: string,
    obsWebsocketPassword: string,
  ) => {
    const defined = Object.fromEntries(
      Object.entries(commands).filter(([, v]) => v !== undefined),
    ) as Partial<Record<BASE.ObsCommandKey, string>>;
    const baseCommands = { ...BASE.DEFAULT_OBS_COMMANDS, ...defined };
    cases.push({
      group,
      input: {
        twitch,
        kick,
        commandUsers,
        commands: defined,
        obsWebsocketUrl,
        obsWebsocketPassword,
      },
      expectedUrl: BASE.baseObsBridgeUrl(ORIGIN, {
        commandUsers,
        obsWebsocketUrl,
        obsWebsocketPassword,
        twitchChannel: twitch,
        kickChannel: kick,
        commands: baseCommands,
      }),
    });
  };

  for (const ch of [...channels, ['', '']]) add('channels', ch, [], {}, '', '');
  for (const key of keys)
    for (const value of commandValues(key).slice(1))
      add('single', ['foo', 'bar'], [], { [key]: value }, '', '');
  for (const row of allPairs({
    channels,
    users,
    wsUrls,
    passwords,
    ...Object.fromEntries(keys.map((k) => [k, commandValues(k)])),
  })) {
    const commands = Object.fromEntries(keys.map((k) => [k, row[k]])) as Partial<
      Record<BASE.ObsCommandKey, string>
    >;
    add(
      'pairwise',
      row.channels as string[],
      row.users as BASE.CommandUser[],
      commands,
      row.wsUrls as string,
      row.passwords as string,
    );
  }
  return { about: ABOUT, origin: ORIGIN, defaults: BASE.DEFAULT_OBS_COMMANDS, cases };
}

// ---------------------------------------------------------------------------------------------

const fixtures: Record<string, Fixture> = {
  'chat-box': chatBox(),
  'emote-wall': emoteWall(),
  'sub-sprout': subSprout(),
  'obs-bridge': obsBridge(),
};

mkdirSync(OUT_DIR, { recursive: true });
const files: string[] = [];
for (const [name, fixture] of Object.entries(fixtures)) {
  const file = `${OUT_DIR}/${name}.json`;
  writeFileSync(file, JSON.stringify(fixture));
  files.push(file);
  console.log(`${name}: ${fixture.cases.length} cases`);
}
// Biome formats every JSON file under src/; its layout also keeps one case to a few lines.
const biome = spawnSync(`${APP_DIR}node_modules/.bin/biome`, ['format', '--write', ...files], {
  stdio: 'inherit',
});
if (biome.status !== 0) process.exit(biome.status ?? 1);
