name: Deploy Twitch Bot Test
on:
  push:
    paths:
      - apps/twitch-bot/**
      - command/**
      - config/**
      - db/**
      - packages/gosenchabot/**
      - "go.mod"
      - "go.sum"
    branches:
      - dev
  pull_request: {}

permissions:
  actions: write
  contents: read

env:
  REGISTRY: registry.fly.io
  MAIN_APP_NAME: senchabot0524tw-dry-dust-1824

jobs:
  build:
    name: Build
    # only build/deploy dev branch on pushes
    if: ${{ (github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Fly Registry Auth
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: x
          password: ${{ secrets.TWITCH_BOT_TEST_FLY_API }}

      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/twitch-bot/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.MAIN_APP_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    # only build/deploy dev branch on pushes
    if: ${{ (github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --app ${{ env.MAIN_APP_NAME }} --image ${{ env.REGISTRY }}/${{ env.MAIN_APP_NAME }}:${{ github.ref_name }}-${{ github.sha }} --config ./apps/twitch-bot/fly.toml"
        env:
          FLY_API_TOKEN: ${{ secrets.TWITCH_BOT_TEST_FLY_API }}

      # - name: Deploy Production
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: superfly/flyctl-actions@1.3
      #   with:
      #     args: "deploy --image ${{ env.REGISTRY }}/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
